GET http://localhost:1234/products

### recuperar producto por id
GET http://localhost:1234/products/4

### Filtrar por categoria
GET http://localhost:1234/products?category=Bebidas+Alcoholicas

### Crear un nuevo producto

POST http://localhost:1234/products
Content-Type: application/json

 {
    "barcode": 1313,
    "name": "Aceite miraflores 4",
    "img": "https:asdfasdf",
    "costPrice": 1800,
    "salePrice": 2450,
    "wholeSalePrice": 2100,
    "category": "abarrotes",
    "inventoryId": "test"
  }
###

POST http://localhost:1234/products
Content-Type: application/json

{
  "barcode": 11111111111,
  "name": "Azucar esmeralda",
  "img": "https:azucarISANsa.com",
  "costPrice": 890,
  "salePrice": 1290,
  "wholeSalePrice": 1000,
  "profit": 30,
  "category": "abarrotes"
}

### Eliminar un producto
DELETE http://localhost:1234/products/4

### actualizar un producto
PATCH http://localhost:1234/products/1
Content-Type: application/json

{
  "sql": "SELECT * FROM products",
  "costPrice": 2300,
  "salePrice": 3190
}
