
### Añadir un nuevo producto al inventario
POST http://localhost:1234/inventory/addProduct/a304eacc-c185-11ee-a148-afb167f07ea4
Content-Type: application/json

{
  "barcode": 1290902391,
  "name": "Azucar esmeralda",
  "img": "https:azucarISANsa.com",
  "costPrice": 890,
  "salePrice": 1290,
  "wholeSalePrice": 1000,
  "profit": 30,
  "trackInventory": true,
  "category": "abarrotes"
}

### Obtener todos los productos por tienda 
GET http://localhost:1234/inventory/products/a304eacc-c185-11ee-a148-afb167f07ea4

### Obtener todos los productos por categoria
GET http://localhost:1234/inventory/products/a304eacc-c185-11ee-a148-afb167f07ea4?category=abarrotes

### Obtener un producto por barcode
GET http://localhost:1234/inventory/product/a304eacc-c185-11ee-a148-afb167f07ea4?barcode=1290902391
